namespace Binance
{

    public class Balance
    {
        public string? Asset { get; set; }
        public string? Free { get; set; }
        public string? Locked { get; set; }
    }

    public class List
    {
        public long? CreateTime { get; set; }
        public string? OrderStatus { get; set; }
        public string? FromAsset { get; set; }
        public string? FromAmount { get; set; }
        public string? ToAsset { get; set; }
        public string? ToAmount { get; set; }
        public string? Ratio { get; set; }
        public string? InverseRatio { get; set; }
        public string? QuoteId { get; set; }
        public long? OrderId { get; set; }
    }


    public class ConvertTradeHistory : IGetResponse
    {
        public List<List>? List { get; set; }
        public long? StartTime { get; set; }
        public long? EndTime { get; set; }
        public int? Limit { get; set; }
        public bool? MoreData { get; set; }
    }


    public class CommissionRates
    {
        public string? Maker { get; set; }
        public string? Taker { get; set; }
        public string? Buyer { get; set; }
        public string? Seller { get; set; }
    }

    public class AccountBalance : IGetResponse
    {
        public int MakerCommission { get; set; }
        public int TakerCommission { get; set; }
        public int BuyerCommission { get; set; }
        public int SellerCommission { get; set; }
        public CommissionRates? CommissionRates { get; set; }
        public bool CanTrade { get; set; }
        public bool CanWithdraw { get; set; }
        public bool CanDeposit { get; set; }
        public bool Brokered { get; set; }
        public bool RequireSelfTradePrevention { get; set; }
        public long UpdateTime { get; set; }
        public string? AccountType { get; set; }
        public List<Balance>? Balances { get; set; }
        public List<string>? Permissions { get; set; }
    }


    public class SymbolPrice : IGetResponse
    {
        public string? Symbol { get; set; }
        public string? Price { get; set; }

    }

    public class ConvertTransfer : IPostResponse
    {
        public string? TranId { get; set; }
        public string? Status { get; set; }
    }


    public class GetQuote : IPostResponse
    {
        public string? QuoteId { get; set; }
        public string? Ratio { get; set; }
        public string? InverseRatio { get; set; }
        public long? ValidTimestamp { get; set; }
        public string? ToAmount { get; set; }
        public string? FromAmount { get; set; }
    }

    public class AcceptQuote : IPostResponse
    {
        public string? OrderId { get; set; }
        public long? CreateTime { get; set; }
        public string? OrderStatus { get; set; }
    }

    public class StatusOrder : IGetResponse
    {
        public long? OrderId { get; set; }
        public string? OrderStatus { get; set; }
        public string? FromAsset { get; set; }
        public string? FromAmount { get; set; }
        public string? ToAsset { get; set; }
        public string? ToAmount { get; set; }
        public string? Ratio { get; set; }
        public string? InverseRatio { get; set; }
        public long? CreateTime { get; set; }
    }

    public enum CurrienciesSymbols
    {
        BTCUSDT,
        BNBUSDT,
        XMRUSDT,
    }


    public enum Assets
    {
        //_1INCH,
        //_1INCHDOWN,
        //_1INCHUP,
        AAVE,
        AAVEDOWN,
        AAVEUP,
        ACA,
        ACH,
        ACM,
        ADA,
        ADADOWN,
        ADAUP,
        ADX,
        AE,
        AERGO,
        AGI,
        AGIX,
        AGLD,
        AION,
        AKRO,
        ALCX,
        ALGO,
        ALICE,
        ALPACA,
        ALPHA,
        ALPINE,
        AMB,
        AMP,
        ANC,
        ANKR,
        ANT,
        ANY,
        APE,
        API3,
        APPC,
        APT,
        AR,
        ARB,
        ARDR,
        ARK,
        ARN,
        ARPA,
        ASR,
        AST,
        ASTR,
        ATA,
        ATM,
        ATOM,
        AUCTION,
        AUD,
        AUDIO,
        AUTO,
        AVA,
        AVAX,
        AXS,
        BADGER,
        BAKE,
        BAL,
        BAND,
        BAR,
        BAT,
        BCC,
        BCD,
        BCH,
        BCHA,
        BCHABC,
        BCHDOWN,
        BCHSV,
        BCHUP,
        BCN,
        BCPT,
        BDOT,
        BEAM,
        BEAR,
        BEL,
        BETA,
        BETH,
        BGBP,
        BICO,
        BIDR,
        BIFI,
        BKRW,
        BLZ,
        BNB,
        BNBBEAR,
        BNBBULL,
        BNBDOWN,
        BNBUP,
        BNT,
        BNX,
        BOND,
        BOT,
        BQX,
        BRD,
        BRL,
        BSW,
        BTC,
        BTCB,
        BTCDOWN,
        BTCST,
        BTCUP,
        BTG,
        BTS,
        BTT,
        BTTC,
        BULL,
        BURGER,
        BUSD,
        BVND,
        BZRX,
        C98,
        CAKE,
        CDT,
        CELO,
        CELR,
        CFX,
        CHAT,
        CHESS,
        CHR,
        CHZ,
        CITY,
        CKB,
        CLOAK,
        CLV,
        CMT,
        CND,
        COCOS,
        COMP,
        COS,
        COTI,
        COVER,
        CREAM,
        CRV,
        CTK,
        CTSI,
        CTXC,
        CVC,
        CVP,
        CVX,
        DAI,
        DAR,
        DASH,
        DATA,
        DCR,
        DEGO,
        DENT,
        DEXE,
        DF,
        DGB,
        DGD,
        DIA,
        DLT,
        DNT,
        DOCK,
        DODO,
        DOGE,
        DOT,
        DOTDOWN,
        DOTUP,
        DREP,
        DUSK,
        DYDX,
        EASY,
        EDO,
        EGLD,
        ELF,
        ENG,
        ENJ,
        ENS,
        EOS,
        EOSBEAR,
        EOSBULL,
        EOSDOWN,
        EOSUP,
        EPS,
        EPX,
        ERD,
        ERN,
        ETC,
        ETH,
        ETHBEAR,
        ETHBULL,
        ETHDOWN,
        ETHUP,
        EUR,
        EVX,
        EZ,
        FARM,
        FET,
        FIDA,
        FIL,
        FILDOWN,
        FILUP,
        FIO,
        FIRO,
        FIS,
        FLM,
        FLOW,
        FLUX,
        FOR,
        FORTH,
        FRONT,
        FTM,
        FTT,
        FUEL,
        FUN,
        FXS,
        GAL,
        GALA,
        GAS,
        GBP,
        GFT,
        GHST,
        GLM,
        GLMR,
        GMT,
        GMX,
        GNO,
        GNS,
        GNT,
        GO,
        GRS,
        GRT,
        GTC,
        GTO,
        GVT,
        GXS,
        HARD,
        HBAR,
        HC,
        HEGIC,
        HFT,
        HIFI,
        HIGH,
        HIVE,
        HNT,
        HOOK,
        HOT,
        HSR,
        ICN,
        ICP,
        ICX,
        ID,
        IDEX,
        IDRT,
        ILV,
        IMX,
        INJ,
        INS,
        IOST,
        IOTA,
        IOTX,
        IQ,
        IRIS,
        JASMY,
        JOE,
        JST,
        JUV,
        KAVA,
        KDA,
        KEEP,
        KEY,
        KLAY,
        KMD,
        KNC,
        KP3R,
        KSM,
        LAZIO,
        LDO,
        LEND,
        LEVER,
        LINA,
        LINK,
        LINKDOWN,
        LINKUP,
        LIT,
        LOKA,
        LOOM,
        LPT,
        LQTY,
        LRC,
        LSK,
        LTC,
        LTCDOWN,
        LTCUP,
        LTO,
        LUN,
        LUNA,
        LUNC,
        MAGIC,
        MANA,
        MASK,
        MATIC,
        MBL,
        MBOX,
        MC,
        MCO,
        MDA,
        MDT,
        MDX,
        MFT,
        MINA,
        MIR,
        MITH,
        MKR,
        MLN,
        MOB,
        MOD,
        MOVR,
        MTH,
        MTL,
        MULTI,
        NANO,
        NAS,
        NAV,
        NBS,
        NBT,
        NCASH,
        NEAR,
        NEBL,
        NEO,
        NEXO,
        NGN,
        NKN,
        NMR,
        NPXS,
        NU,
        NULS,
        NXS,
        OAX,
        OCEAN,
        OG,
        OGN,
        OM,
        OMG,
        ONE,
        ONG,
        ONT,
        OOKI,
        OP,
        ORN,
        OSMO,
        OST,
        OXT,
        PAX,
        PAXG,
        PEOPLE,
        PERL,
        PERP,
        PHA,
        PHB,
        PHX,
        PIVX,
        PLA,
        PLN,
        PNT,
        POA,
        POE,
        POLS,
        POLY,
        POLYX,
        POND,
        PORTO,
        POWR,
        PPT,
        PROM,
        PROS,
        PSG,
        PUNDIX,
        PYR,
        QI,
        QKC,
        QLC,
        QNT,
        QSP,
        QTUM,
        QUICK,
        RAD,
        RAMP,
        RARE,
        RAY,
        RCN,
        RDN,
        REEF,
        REI,
        REN,
        RENBTC,
        REP,
        REQ,
        RGT,
        RIF,
        RLC,
        RNDR,
        RON,
        ROSE,
        RPL,
        RPX,
        RSR,
        RUB,
        RUNE,
        RVN,
        SALT,
        SAND,
        SANTOS,
        SC,
        SCRT,
        SFP,
        SHIB,
        SKL,
        SKY,
        SLP,
        SNGLS,
        SNM,
        SNT,
        SNX,
        SOL,
        SPARTA,
        SPELL,
        SRM,
        SSV,
        STEEM,
        STG,
        STMX,
        STORJ,
        STORM,
        STPT,
        STRAT,
        STRAX,
        STX,
        SUB,
        SUN,
        SUPER,
        SUSD,
        SUSHI,
        SUSHIDOWN,
        SUSHIUP,
        SWRV,
        SXP,
        SXPDOWN,
        SXPUP,
        SYN,
        SYS,
        T,
        TCT,
        TFUEL,
        THETA,
        TKO,
        TLM,
        TNB,
        TNT,
        TOMO,
        TORN,
        TRB,
        TRIBE,
        TRIG,
        TROY,
        TRU,
        TRX,
        TRXDOWN,
        TRXUP,
        TRY,
        TUSD,
        TUSDB,
        TVK,
        TWT,
        UAH,
        UFT,
        UMA,
        UNFI,
        UNI,
        UNIDOWN,
        UNIUP,
        USDC,
        USDP,
        USDS,
        USDSB,
        USDT,
        UST,
        USTC,
        UTK,
        VAI,
        VEN,
        VET,
        VGX,
        VIA,
        VIB,
        VIBE,
        VIDT,
        VITE,
        VOXEL,
        VTHO,
        WABI,
        WAN,
        WAVES,
        WAXP,
        WBTC,
        WIN,
        WING,
        WINGS,
        WNXM,
        WOO,
        WPR,
        WRX,
        WTC,
        XEC,
        XEM,
        XLM,
        XLMDOWN,
        XLMUP,
        XMR,
        XNO,
        XRP,
        XRPBEAR,
        XRPBULL,
        XRPDOWN,
        XRPUP,
        XTZ,
        XTZDOWN,
        XTZUP,
        XVG,
        XVS,
        XZC,
        YFI,
        YFIDOWN,
        YFII,
        YFIUP,
        YGG,
        YOYO,
        ZAR,
        ZEC,
        ZEN,
        ZIL,
        ZRX
    }


}
